name: Build and Release

on:
  push:
    tags:
      - 'v*'
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: macOS-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Build the app
      run: npm run make  # Replace with your build command

    - name: App location
      id: app_location
      run: |
        fullpath_arm64=$(readlink -f ./out/make/*-arm64.dmg)
        fullpath_x64=$(readlink -f ./out/make/*-x64.dmg)
        echo "fullpath_arm64=${fullpath_arm64}" >> $GITHUB_OUTPUT
        echo "fullpath_x64=${fullpath_x64}" >> $GITHUB_OUTPUT
        echo "tagname=$(echo $GITHUB_REF | sed 's|refs/tags/||')" >> $GITHUB_OUTPUT

    - name: Create release
      uses: softprops/action-gh-release@v1
      with:
        files: ${{ steps.app_location.outputs.fullpath_x64 }} ${{ steps.app_location.outputs.fullpath_arm64 }}
        tag_name: ${{ steps.app_location.outputs.tagname }}
        name: Release ${{ steps.app_location.outputs.tagname }}
        draft: false
        prerelease: false
