name: Build and Release

on:
  push:
    tags:
      - 'v*'
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token

jobs:
  build:
    runs-on: macOS-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Build the app
      run: npm run make  # Replace with your build command

    - name: App location
      id: app_location
      run: |
        fullpath_arm64=$(readlink -f ./out/make/*-arm64.dmg)
        fullpath_x64=$(readlink -f ./out/make/*-x64.dmg)
        echo "fullpath_arm64=${fullpath_arm64}" >> $GITHUB_OUTPUT
        echo "fullpath_x64=${fullpath_x64}" >> $GITHUB_OUTPUT
        echo "tagname=$(echo $GITHUB_REF | sed 's|refs/tags/||')" >> $GITHUB_OUTPUT

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      with:
        tag_name: ${{ steps.app_location.outputs.tagname }}
        release_name: Release ${{ steps.app_location.outputs.tagname }}
        draft: false
        prerelease: false

    - name: Upload Release Asset x64
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ${{ steps.app_location.outputs.fullpath_x64 }}
        asset_name: ChatGPT_${{ steps.app_location.outputs.tagname }}_x64.dmg
        asset_content_type: application/x-dmg
    
    - name: Upload Release Asset arm64
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ${{ steps.app_location.outputs.fullpath_arm64 }}
        asset_name: ChatGPT_${{ steps.app_location.outputs.tagname }}_arm64.dmg
        asset_content_type: application/x-dmg
